=== perez25/PLC/PRI/DTD/fotos.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT fotos (foto+) >
<!ELEMENT foto (quando,quem,facto,onde?)>
<!ELEMENT quando (#PCDATA)>
<!ELEMENT quem (#PCDATA)>
<!ELEMENT facto (#PCDATA)>
<!ELEMENT onde (#PCDATA)>


<!ATTLIST foto ficheiro CDATA #REQUIRED>
<!ATTLIST quando data CDATA #REQUIRED>

=== perez25/PLC/PRI/XML/fotos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fotos SYSTEM "file:/Users/Perez_25/Desktop/fotos.dtd">
<fotos>
    <foto ficheiro="cenz">
        <quando data="12-12-2012"></quando>
        <quem>Tó</quem>
        <facto>Na ribeira</facto>
    </foto>
    <foto ficheiro="cenz2">
        <quando data="13-12-2012"></quando>
        <quem>Marcos</quem>
        <facto>Na Praça</facto>
    </foto>
 </fotos>
