=== perez25/PLC/PRI/SCHEMAS/arquivo_biografias.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1">

    <xs:element name="arquivo_biografias">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="biografia"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="biografia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="data" type="xs:date"/>
                <xs:element name="sujeito" type="xs:string"/>
                <xs:element name="local" type="xs:string"/>
                <xs:element minOccurs="0" name="evento" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== perez25/PLC/PRI/XML/biografias.xml
<?xml version="1.0" encoding="UTF-8"?>
<arquivo_biografias xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Users/Perez_25/Downloads/arquivo_biografias.xsd">
    <biografia>
        <data>1992-12-03</data>
        <sujeito>Sérgio Simões</sujeito>
        <local>Aveiro</local>
        <evento>Aniversário do António</evento>
    </biografia>
    
    <biografia>
        <data>1992-12-03</data>
        <sujeito>Sérgio Simões</sujeito>
        <local>Aveiro</local>
        <evento>Aniversário do António</evento>
    </biografia>
    
</arquivo_biografias>
