=== perez25/PLC/PRI/SCHEMAS/jornal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1">

    <xs:element name="jornal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cabeçalho">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="edição" type="xs:string"/>
                            <xs:element name="data" type="xs:date"/>
                            <xs:element name="local" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id_jornal" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="corpo">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="secção">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:element ref="secção"/>
                                        <xs:element name="artigo">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="titulo" type="xs:string"/>
                                                  <xs:element name="sub_titulo" type="xs:string"/>
                                                  <xs:element name="data" type="xs:date"/>
                                                  <xs:element name="autor" type="xs:string"/>
                                                  <xs:element ref="p"/>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:string"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                    <xs:attribute name="id" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="fecho"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="p">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="imagem" type="xs:string"/>
                <xs:element name="nome_pessoa" type="xs:string"/>
                <xs:element name="lugar" type="xs:string"/>
                <xs:element name="data" type="xs:date"/>
                <xs:element name="referencia">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome"/>
                        </xs:sequence>
                        <xs:attribute name="xref" type="xs:IDREF"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="artigo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="sub_titulo" type="xs:string"/>
                <xs:element name="data" type="xs:date"/>
                <xs:element name="autor" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="secção">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="secção"/>
                <xs:element name="artigo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="sub_titulo" type="xs:string"/>
                            <xs:element name="data" type="xs:date"/>
                            <xs:element name="autor" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== perez25/PLC/PRI/XML/jornal.xml
<?xml version="1.0" encoding="UTF-8"?>
<jornal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Users/Perez_25/Documents/Universidade/Mestrado/PLC/PED/SCHEMAS/jornal.xsd">
    <cabeçalho>
        <edição>Opinião Perez</edição>
        <data>2015-02-02</data>
        <local>3B</local>
    </cabeçalho>
    <corpo>
      <secção id="Crónica da semana">
          <artigo id="benfica">
                    <titulo>Crónica da Semana</titulo>
                    <sub_titulo>Benfica ganha de novo</sub_titulo>
                    <data>2015-02-02</data>
                    <autor>Perez</autor>
                    <p>
                      <nome_pessoa>Jonas marca mais um golo!</nome_pessoa>  
                    </p>
                </artigo>
         
              <artigo id="porto">
              <titulo>FCP</titulo>
              <sub_titulo>Mais um jogo ganho facilmente</sub_titulo>
              <data>2015-02-02</data>
              <autor>David Rodrigues</autor>
              <p>
                 <imagem> cenz</imagem> 
              </p>
          </artigo>
          
          <secção id="Futsal">
              <artigo>
                  <titulo>Benfica ganha em braga</titulo>
                  <sub_titulo>Resultado final 5 -3 </sub_titulo>
                  <data>2015-02-01</data>
                  <autor>Rodrigo Moreno</autor>
              </artigo>
              
          </secção>
            </secção>
      
            
        
    </corpo>
    <fecho></fecho>
</jornal>
