=== perez25/PLC/PRI/SCHEMAS/report2014.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="http://elpri.di.uminho.pt/report"
    xmlns:l="http://elpri.di.uminho.pt/list" xmlns:p="http://elpri.di.uminho.pt/paragraph"
    xmlns:r="http://elpri.di.uminho.pt/report">
    <xs:import namespace="http://elpri.di.uminho.pt/paragraph" schemaLocation="paragraph2014.xsd"/>
    <xs:import namespace="http://elpri.di.uminho.pt/list" schemaLocation="list2014.xsd"/>
    <xs:element name="report">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="front-matter">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="meta">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element minOccurs="0" name="subtitle" type="xs:string"/>
                                        <xs:element name="authors">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="author">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="name" type="xs:string"/>
                                                  <xs:element minOccurs="0" name="email"
                                                  type="xs:string"/>
                                                  <xs:element minOccurs="0" name="id"
                                                  type="xs:string"/>
                                                  <xs:element minOccurs="0" name="photo">
                                                  <xs:complexType>
                                                  <xs:attribute name="path" type="xs:string"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="date" type="xs:date"/>
                                        <xs:element minOccurs="0" name="affil" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="acknowledgements">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" ref="p:p"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="abstract">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" ref="p:p"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="toc"/>
                            <xs:element minOccurs="0" name="lot"/>
                            <xs:element name="lof"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="body">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="section">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:choice maxOccurs="unbounded">
                                            <xs:element ref="p:p"/>
                                            <xs:element name="subsection">
                                                <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="title" type="xs:string"/>
                                                  <xs:choice maxOccurs="unbounded">
                                                  <xs:element ref="p:p"/>
                                                  <xs:element name="subsubsection">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="title" type="xs:string"/>
                                                  <xs:choice maxOccurs="unbounded">
                                                  <xs:element ref="p:p"/>
                                                  <xs:group ref="l:list"/>
                                                  </xs:choice>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:group ref="l:list"/>
                                                  </xs:choice>
                                                  </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:choice>
                                        <xs:group ref="l:list"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="back-matter">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="appendix-list">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="appendix">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="title" type="xs:string"/>
                                                  <xs:choice maxOccurs="unbounded">
                                                  <xs:element ref="p:p"/>
                                                  <xs:element name="subsection">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="title" type="xs:string"/>
                                                  <xs:choice maxOccurs="unbounded">
                                                  <xs:element ref="p:p"/>
                                                  <xs:element name="subsubsection">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="title" type="xs:string"/>
                                                  <xs:choice maxOccurs="unbounded">
                                                  <xs:element ref="p:p"/>
                                                  <xs:group ref="l:list"/>
                                                  </xs:choice>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:group ref="l:list"/>
                                                  </xs:choice>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:choice>
                                                  <xs:group ref="l:list"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="bibliography">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="bibitem">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="authors">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="author">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="name" type="xs:string"/>
                                                  <xs:element minOccurs="0" name="email"
                                                  type="xs:string"/>
                                                  <xs:element minOccurs="0" name="id"
                                                  type="xs:string"/>
                                                  <xs:element minOccurs="0" name="photo">
                                                  <xs:complexType>
                                                  <xs:attribute name="path" type="xs:string"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="title" type="xs:string"/>
                                                  <xs:element name="date" type="xs:date"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== perez25/PLC/PRI/XML/teste.xml
<?xml version="1.0" encoding="UTF-8"?>
<report xmlns="http://elpri.di.uminho.pt/report"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://elpri.di.uminho.pt/report file:/Users/Perez_25/Documents/Universidade/PL-%20MESTRADO/PED/report2014.xsd">
    <front-matter>
        <meta>
            <title></title>
            <authors>
                <author>
                    <name></name>
                </author>
            </authors>
            <date>2014-12-15</date>
        </meta>
        <acknowledgements>
            <p xmlns="http://elpri.di.uminho.pt/paragraph">Isto é um teste</p>
        </acknowledgements>
        <abstract>
            <p xmlns="http://elpri.di.uminho.pt/paragraph">Isto é um teste</p>
        </abstract>
        <toc></toc>
        <lof></lof>
    </front-matter>
    <body>
        <section>
            <title>Primeira seçao</title>
        </section>
    </body>
    <back-matter/>
        
        
    
</report>
