=== perez25/PLC/PRI/Ficheiros/cv-europass.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT cv_europass (informacao_pessoal, posto_candidato?, experiencia_prof?, educacao_formacao, competencias_pessoais?, informacao_adicional?, anexo?) >

<!-- pessoal -->
<!ELEMENT informacao_pessoal (nome,morada,telefone,email,sexo?,datanascimento?,nacionalidades?,foto?) >

<!ELEMENT nome (nome_proprio, apelido) >
<!ELEMENT nome_proprio (#PCDATA) >
<!ELEMENT apelido (#PCDATA) >

<!ELEMENT morada (rua, cod_postal, cidade, pais) >
<!ELEMENT rua (#PCDATA) >
<!ELEMENT cod_postal (#PCDATA) >
<!ELEMENT cidade (#PCDATA) >
<!ELEMENT pais (#PCDATA) >

<!ELEMENT telefone (tipo_telefone, numero) >
<!ELEMENT tipo_telefone (#PCDATA) >
<!ELEMENT numero (#PCDATA) >

<!ELEMENT email (#PCDATA) >
<!ELEMENT sexo (#PCDATA) >
<!ELEMENT datanascimento (data) >
<!ELEMENT data (dia,mes,ano) >
<!ELEMENT dia (#PCDATA) >
<!ELEMENT mes (#PCDATA) >
<!ELEMENT ano (#PCDATA) >
<!ELEMENT nacionalidades (nacionalidade+) >
<!ELEMENT nacionalidade (#PCDATA) >
<!ELEMENT foto (xref) >
<!ELEMENT xref (#PCDATA) >
<!ATTLIST xref
            url CDATA #REQUIRED >
            

<!-- posto a que se candidata -->
<!ELEMENT posto_candidato (tipo_candidatura, posto_trabalho)+ >
<!ELEMENT tipo_candidatura (#PCDATA) >
<!ELEMENT posto_trabalho (#PCDATA) >      

<!-- exp. profissional -->
<!ELEMENT experiencia_prof (ano_entrada,ano_conclusao, cargo_ocupado, empregador, informacao_adicional) > 
<!ELEMENT cargo_ocupado (#PCDATA) >

<!ELEMENT empregador (nome_proprio, cidade, pais) >

<!-- educaçao e formaçao -->
<!ELEMENT educacao_formacao (curso,ano_entrada?,ano_conclusao,local_formacao, informacao_adicional?)>

<!ELEMENT curso (#PCDATA) >
<!ELEMENT ano_entrada (data) >
<!ELEMENT ano_conclusao (data) >
<!ELEMENT local_formacao (nome_proprio, cidade, pais) >

<!-- competencias pessoais -->

<!ELEMENT competencias_pessoais (lingua_materna, outras_linguas?, competencias_comunicacao?, competencias_organizacao?, competencias_trabalho?, competencias_informaticas?, outras?, carta_conducao?) >
<!ELEMENT lingua_materna (#PCDATA)>
<!ELEMENT outras_linguas (lingua, compreender,falar, escrever, diploma?) >
<!ELEMENT lingua (#PCDATA) >

<!ELEMENT compreender (compreensao_oral, leitura) >
<!ELEMENT compreensao_oral (#PCDATA) >
<!ELEMENT leitura (#PCDATA) >

<!ELEMENT falar (interacao_oral, producao_oral) >
<!ELEMENT interacao_oral (#PCDATA) >
<!ELEMENT producao_oral (#PCDATA) >

<!ELEMENT escrever (#PCDATA) >

<!ELEMENT diploma (anexo) >

<!ELEMENT competencias_comunicacao (informacao_adicional) >
<!ELEMENT competencias_organizacao (informacao_adicional) >
<!ELEMENT competencias_trabalho (informacao_adicional) >
<!ELEMENT competencias_informaticas (informacao_adicional) > 
<!ELEMENT outras (informacao_adicional) > 
<!ELEMENT carta_conducao (tipo) >
<!ELEMENT tipo (#PCDATA) >
<!ATTLIST tipo
          tipocarta CDATA #REQUIRED>

<!-- informaçao adicional -->

<!ELEMENT informacao_adicional (p+) >
<!ELEMENT p (#PCDATA|b|i|u|ackron|xref)* >
<!ELEMENT b (#PCDATA|i|u|ackron|xref)* >
<!ELEMENT i (#PCDATA|b|u|ackron|xref)* >
<!ELEMENT u (#PCDATA|b|i|ackron|xref)* >
<!ELEMENT ackron (#PCDATA) >

<!-- anexo -->

<!ELEMENT anexo (xref+) >

=== perez25/PLC/PRI/Ficheiros/cv-europass.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv_europass SYSTEM "file:/Applications/oxygen/Ficheiros/cv-europass.dtd">
<cv_europass>
    <informacao_pessoal>
        <nome>
            <nome_proprio>Hélder Márcio</nome_proprio>
            <apelido>Loureiro da Rocha</apelido>
        </nome>
        <morada>
            <rua>Rua de Fontes 584</rua>
            <cod_postal>4580-315</cod_postal>
            <cidade>Cete</cidade>
            <pais>Portugal</pais>
        </morada>
        <telefone>
            <tipo_telefone>Telemóvel</tipo_telefone>
            <numero>915958226</numero>
        </telefone>
        <email>helder.1124.30@gmail.com</email>
        <sexo>Masculino</sexo>
        <datanascimento>
            <data>
                <dia>03</dia>
                <mes>12</mes>
                <ano>1991</ano>
            </data>
        </datanascimento>
        <nacionalidades>
            <nacionalidade>Portuguesa</nacionalidade>
        </nacionalidades>
        <foto>
            <xref url="www.foto.com">foto legendada</xref>
        </foto>
    </informacao_pessoal>
    <educacao_formacao>
        <curso>Licenciatura em Engenharia Informática</curso>
        <ano_entrada>
            <data>
                <dia>15</dia>
                <mes>09</mes>
                <ano>2009</ano>
            </data>
        </ano_entrada>
        <ano_conclusao>
            <data>
                <dia>15</dia>
                <mes>09</mes>
                <ano>2014</ano>
            </data>
        </ano_conclusao>
        <local_formacao>
            <nome_proprio>Universidade do Minho</nome_proprio>
            <cidade>braga</cidade>
            <pais>Portugal</pais>
        </local_formacao>
    </educacao_formacao>
    <competencias_pessoais>
        <lingua_materna>Portuguesa</lingua_materna>
        <outras_linguas>
            <lingua>Inglês</lingua>
            <compreender>
                <compreensao_oral>B1</compreensao_oral>
                <leitura>B1</leitura>
            </compreender>
            <falar>
                <interacao_oral>B1</interacao_oral>
                <producao_oral>B1</producao_oral>
            </falar>
            <escrever>B1</escrever>
        </outras_linguas>
        <competencias_informaticas>
            <informacao_adicional>
                <p>Competência em <b>dtd</b> e <b>xml's</b></p>
                <p>Java, C++, C, Haskell</p>
            </informacao_adicional>
        </competencias_informaticas>
        <carta_conducao>
            <tipo tipocarta="B">B</tipo>
        </carta_conducao>
    </competencias_pessoais>
    <informacao_adicional>
        <p>Federado em futebol 6 anos, desde iniciado a júnior.</p>
        <p>Candidato de uma lista, cargo de tesoureiro, para a Associação Académica da Universidade do Minho.</p>
    </informacao_adicional>
</cv_europass>
