=== perez25/PLC/GCS/TPC_PL/PRI_a64283_t2/cv_europass.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT  europass (informação-pessoal ,posto-de-trabalho, experiencias-profissionais,educações-formações) >
<!ELEMENT posto-de-trabalho (#PCDATA) >
<!ELEMENT  informação-pessoal (nome,morada,contacto,sexo,nacionalidade) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT sexo (#PCDATA) >
<!ELEMENT nacionalidade (#PCDATA) >

<!ELEMENT morada (rua,numero,código-postal,localidade,distrito,país) >
<!ELEMENT numero (#PCDATA) >
<!ELEMENT rua (#PCDATA) >
<!ELEMENT código-postal (#PCDATA) >
<!ELEMENT distrito (#PCDATA) >
<!ELEMENT país (#PCDATA) >
<!ELEMENT localidade (#PCDATA) >

<!ELEMENT contacto (numero+,email,outros) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT outros (facebook,google,twitter,outro*) >
<!ELEMENT facebook (#PCDATA) >
<!ELEMENT google (#PCDATA) >
<!ELEMENT twitter (#PCDATA) >
<!ELEMENT outro (#PCDATA)  >
<!ELEMENT experiencias-profissionais (experiencia-profissional*) >
<!ELEMENT experiencia-profissional (data-inicio,data-fim,posto-de-trabalho,morada,info) >
<!ELEMENT data-inicio (mes,ano) >
<!ELEMENT data-fim (mes,ano) >
<!ELEMENT ano (#PCDATA) >
<!ELEMENT mes (#PCDATA) >
<!ELEMENT info (#PCDATA) >



<!ELEMENT educações-formações (educação-formação+) >
<!ELEMENT educação-formação (data-inicio, data-fim , nome-formação,entidade-formação, tópicos-de-formação) >
<!ELEMENT nome-formação (#PCDATA) >
<!ELEMENT entidade-formação (#PCDATA) >
<!ELEMENT tópicos-de-formação (tópico-de-formação+) >
<!ELEMENT tópico-de-formação (#PCDATA) >

=== perez25/PLC/GCS/TPC_PL/PRI_a64283_t2/europass.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE europass SYSTEM "file:/Users/Perez_25/Desktop/cv_europass.dtd">
<europass>
    <informação-pessoal>
        <nome>Sérgio Manuel Pereira Simões</nome>
        <morada>
            <rua>Lagoncinha</rua>
            <numero>6</numero>
            <código-postal>3780 599</código-postal>
            <localidade>Torres,Vilarinho do Bairro</localidade>
            <distrito>Aveiro</distrito>
            <país>Portugal</país>
        </morada>
        <contacto>
            <numero>911173130</numero>
            <email>sergiohero@gmail.com</email>
            <outros>
                <facebook>sergiosimoes25</facebook>
                <google>sergiohero@gmail.com</google>
                <twitter></twitter>
            </outros>
        </contacto>
        <sexo>Masculino</sexo>
        <nacionalidade>Portuguesa</nacionalidade>
    </informação-pessoal>
    <posto-de-trabalho>Engenheiro Informático</posto-de-trabalho>
    <experiencias-profissionais></experiencias-profissionais>
    <educações-formações>
        <educação-formação>
            <data-inicio>
                <mes>9</mes>
                <ano>2011</ano>
            </data-inicio>
            <data-fim>
                <mes>6</mes>
                <ano>2014</ano>
            </data-fim>
            <nome-formação>Licenciatura em Engenharia Informática</nome-formação>
            <entidade-formação>Universidade do Minho</entidade-formação>
            <tópicos-de-formação>
             <tópico-de-formação>C++</tópico-de-formação>   
             <tópico-de-formação>Java</tópico-de-formação>
            </tópicos-de-formação>
        </educação-formação>
    </educações-formações>
</europass>
