=== perez25/PLC/PRI/Exame_epoca_especial/exame.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1">

    <xs:element name="exame">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cabeçalho">
                    <xs:complexType>
                        <xs:sequence minOccurs="1">
                            <xs:element name="uc" type="xs:string"/>
                            <xs:element name="tipo_exame" type="xs:string"/>
                            <xs:element name="data" type="xs:date"/>
                            <xs:element name="hora" type="xs:string"/>
                            <xs:element name="aviso" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="corpo">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="imagem">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="descrição" type="xs:string"/>
                                        <xs:element name="path" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="questão">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="1">
                                        <xs:element name="numero" type="xs:integer"/>
                                        <xs:element name="texto" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== perez25/PLC/PRI/Exame_epoca_especial/exame.xml
<?xml version="1.0" encoding="UTF-8"?>
<exame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Users/Perez_25/Documents/Universidade/Mestrado/PLC/PED/Exame_epoca_especial/exame.xsd">
    <cabeçalho>
        <uc></uc>
        <tipo_exame></tipo_exame>
        <data>2014-10-14</data>
        <hora>14:00</hora>
         <aviso>Dispõe de 2:00 horas para realizar este exame;
                Leia as questões com toda a atenção
            e responda com calma e clareza em folha convencional
          </aviso>
    </cabeçalho>
    <corpo>
        <imagem>
            <descrição>Considere o seguinte excerto dum documento de registo bibliográfico 
                (parta do princípio de que todos os registos são semelhantes
                `aquele que se apresenta):</descrição>
            <path>ficheiro_xml</path>
        </imagem>
        <questão>
            <numero>1</numero>
            <texto>Desenvolva um DTD para documentos com uma estrutura semelhante
                `aquela que está representada no excerto.</texto>
        </questão>
        <questão>
            <numero>2</numero>
            <texto> Desenvolva uma stylesheet XSL para extrair todas as chaves 
                (o atributo ID de BIBLIOENTRY) e apre- sent ́a-las por ordem alfab ́etica.</texto>
        </questão>
    </corpo>
</exame>
