=== perez25/PLC/PRI/Sérgio Simões/pr_a64283_t4/project-record.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT project-record (meta, abstract?, workteam, logs?, deliverables?) >
<!ELEMENT meta (title,subtitle?, key-name, supervisors, begin-date, end-date?) >

<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT key-name (#PCDATA) >

<!ELEMENT supervisors (supervisor+) >
<!ELEMENT supervisor (name, email, homepage) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT homepage (#PCDATA) >
<!ELEMENT email (#PCDATA) >

<!ELEMENT begin-date (#PCDATA) >
<!ELEMENT end-date (#PCDATA) >

<!ELEMENT abstract (p+) >
<!-- elemento paragrafo b = bold i = italico etc etc-->
<!ELEMENT p (#PCDATA|b|i|u|ackron|xref)* >
<!ELEMENT b (#PCDATA|i|u|ackron|xref)* >
<!ELEMENT i (#PCDATA|b|u|ackron|xref)* >
<!ELEMENT u (#PCDATA|b|i|ackron|xref)* >
<!ELEMENT ackron (#PCDATA) >
<!ELEMENT xref (#PCDATA) >
<!ATTLIST xref
            url CDATA #REQUIRED >
 

<!ELEMENT workteam (student+) >
<!ELEMENT student (ident, name, email) >

<!ELEMENT ident (#PCDATA) >

<!ELEMENT logs (log+) >
<!ELEMENT log (date, description) >

<!ELEMENT date (#PCDATA) >
<!ELEMENT description (p+) >

<!ELEMENT deliverables (xref+) >

=== perez25/PLC/PRI/XML/project-record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "file:/Users/Perez_25/Desktop/project-record.dtd">
<project-record>
    <meta>
        <title>TPC3</title>
        <key-name>a66jbj</key-name>
        <supervisors>
            <supervisor>
                <name>José Carlos Ramalho</name>
                <email>jcr@di.uminho.pt</email>
                <homepage>http://www3.di.uminho.pt/~jcr/</homepage>
            </supervisor>
        </supervisors>
        <begin-date>Outubro 2014</begin-date>
        <end-date>Outubro 2014</end-date>
    </meta>
    <abstract>
        <p>
         Para a elaboração deste TPC era necessário requer conhecimentos
         sobre <b>XSL</b>.
          Este descreve como fazer o “display” de  um documento XML. <b>XSL</b> é uma espécie stylesheets para xml,
         do mesmo modo que CSS são stylesheets para HTML. 
         O <b>XSL</b> engloba três partes :</p>
        <p> XPATH - linguagem para definir partes de um documentos XML;</p>
        <p>XSLT - linguagem para tranformar documentos XML;</p>            
        <p> XSL-FO - linguagem para definir documentos XML;</p>
        <p><b>Objectivo</b></p>
       
     <p>Criar uma stylesheet que processe informação sobre a submissão de trabalhos práticos, e criar uma página HTML onde seja fácil consultar a informação das várias submissões.
       Por fim completar o project-record.</p>
        </abstract>
    <workteam>
        <student>
            <ident>64283</ident>
            <name>Sérgio Manuel Pereira Simões</name>
            <email>sergiohero@gmail.com</email>
        </student>
        <student>
            <ident>64283</ident>
            <name>Sérgio Manuel Pereira Simões</name>
            <email>sergiohero@gmail.com</email>
        </student>
        
    </workteam>
   <deliverables>
       <xref url="file:/Users/Perez_25/Desktop/tps.html">tps.html</xref>
       <xref url="file:/Users/Perez_25/Desktop/tps.xml">tps.xml</xref>
       <xref url="file:/Users/Perez_25/Desktop/tps.dtd">tps.dtd</xref>
       <xref url="file:/Users/Perez_25/Desktop/tps.dtd">tps.xsl</xref>
       <xref url="file:/Users/Perez_25/Desktop/project-record.dtd">project-record.dtd</xref>
       <xref url="file:/Users/Perez_25/Desktop/project-record.xml">project-record.xml</xref>
       <xref url="file:/Users/Perez_25/Desktop/project-record.xsl">project-record.xsl</xref>
       <xref url="file:/Users/Perez_25/Desktop/project-record.html">project-record.html</xref>
   </deliverables>
</project-record>

=== perez25/PLC/PRI/Sérgio Simões/pr_a64283_t4/project-record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "file:/Users/Perez_25/Downloads/Sérgio Simões/TPC_4/project-record.dtd">
<project-record>
    <meta>
        <title>TPC4</title>
        <key-name>a66jbj</key-name>
        <supervisors>
            <supervisor>
                <name>José Carlos Ramalho</name>
                <email>jcr@di.uminho.pt</email>
                <homepage>http://www3.di.uminho.pt/~jcr/</homepage>
            </supervisor>
        </supervisors>
        <begin-date>Novembro 2014</begin-date>
        <end-date>Novembro 2014</end-date>
    </meta>
    <abstract>
  
        
        <p><b>Objectivo</b></p>
       
     <p>Criar uma página html com a ajuda do xsl extraindo os dados do ficheiro XML <i>Agenda_sonora</i>.</p>
        </abstract>
    <workteam>
        <student>
            <ident>64283</ident>
            <name>Sérgio Manuel Pereira Simões</name>
            <email>sergiohero@gmail.com</email>
        </student>
        
        
    </workteam>
   <deliverables>
       <xref url="Agenda_Sonora.xml">Agenda_sonora.xml</xref>
       <xref url="Agenda_Sonora.xsl">AgendaSonora.xsl</xref>
       <xref url="project-record.xml">project-record.xml</xref>
       <xref url="project-record.xsl">project-record.xsl</xref>
   </deliverables>
</project-record>
